### ISSUE TITLE
Connecting To Prefab Brush Unity

### ISSUE THREAD

**Issue by smkplus** [Roland09/PrefabPainter#7]
your tool is great but unfortunately It doesn't support unity's TileMap 
so I decided to change your code to support the TileMap and Prefab brush

![Record_2021_09_28_11_55_52_989](https://user-images.githubusercontent.com/16706911/135051450-018c3ec7-46f1-4837-acbc-e239629fcc1f.gif)

**Comment by Roland09** [comment]
That looks exciting and fluent. Thanks for sharing!

**Comment by smkplus** [comment]
oh sorry I put the Issue on wrong repository
anyway you can use this tool
https://github.com/smkplus/prefab-painter
