### ISSUE TITLE
Spline tool clones prefab

### ISSUE THREAD

**Issue by fender** [Roland09/PrefabPainter#9]
@Roland09 Excellent tool. Life saver even!

Is there a reason why for the brush prefab painting the objects remain as prefabs in the scene but for the spline tool it clones them and they lose their prefab link?

**Comment by Roland09** [comment]
Thank you @fender, there's no reason anymore. I changed it to instantiate prefab.

**Comment by fender** [comment]
> Thank you @fender, there's no reason anymore. I changed it to instantiate prefab.

How can I update YAPP? When I clicked Update in the package manager it says its already up to date.
![image](https://user-images.githubusercontent.com/1436470/159140202-830a0886-0d3f-4a54-b95d-3f1ed6e4df7e.png)

**Comment by Roland09** [comment]
I pushed an update to the version number. It should show 0.9.5 now and update.
